// import React, { useRef } from "react";
// import { useLoader } from "@react-three/fiber";
// import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
// import { clone } from "three/examples/jsm/utils/SkeletonUtils";
// import { useFrame } from "@react-three/fiber";

// export default function Keys2({ position, rotation }) {
//   const gltf = useLoader(GLTFLoader, "./Keychain2.glb");
//   const clonedScene = clone(gltf.scene);
//   //   useFrame((state, delta) => (clonedScene.rotation.y += delta));

//   return (
//     <primitive object={clonedScene} position={position} rotation={rotation} />
//   );
// }

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Keys2(props) {
  const { nodes, materials } = useGLTF("/Keychain2.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="EightBall"
        position={[9.784, 9.733, 0.766]}
        rotation={[-1.653, -0.016, -2.925]}
        scale={0.511}
      >
        <mesh
          name="ring"
          castShadow
          receiveShadow
          geometry={nodes.ring.geometry}
          material={materials["マテリアル.001"]}
        />
        <mesh
          name="ring_1"
          castShadow
          receiveShadow
          geometry={nodes.ring_1.geometry}
          material={materials["Black-8Ball"]}
        />
        <mesh
          name="ring_2"
          castShadow
          receiveShadow
          geometry={nodes.ring_2.geometry}
          material={materials["8Ball"]}
        />
      </group>
      <group
        name="GoKey"
        position={[3.09, 9.641, 0.966]}
        rotation={[-1.595, 0, -2.927]}
        scale={0.511}
      >
        <mesh
          name="ring002"
          castShadow
          receiveShadow
          geometry={nodes.ring002.geometry}
          material={materials["マテリアル.001"]}
        />
        <mesh
          name="ring002_1"
          castShadow
          receiveShadow
          geometry={nodes.ring002_1.geometry}
          material={materials.GoBlack}
        />
        <mesh
          name="ring002_2"
          castShadow
          receiveShadow
          geometry={nodes.ring002_2.geometry}
          material={materials.GoWhite}
        />
      </group>
      <group
        name="HotelKey"
        position={[16.018, 9.693, 0.728]}
        rotation={[-1.595, 0, -2.927]}
        scale={0.511}
      >
        <mesh
          name="ring001"
          castShadow
          receiveShadow
          geometry={nodes.ring001.geometry}
          material={materials["マテリアル.001"]}
        />
        <mesh
          name="ring001_1"
          castShadow
          receiveShadow
          geometry={nodes.ring001_1.geometry}
          material={materials.HotelWhite}
        />
        <mesh
          name="ring001_2"
          castShadow
          receiveShadow
          geometry={nodes.ring001_2.geometry}
          material={materials["Black-Text"]}
        />
      </group>
      <group
        name="Key"
        position={[-2.38, 9.416, 0.189]}
        rotation={[-1.595, 0, -2.927]}
        scale={0.511}
      >
        <mesh
          name="ring003"
          castShadow
          receiveShadow
          geometry={nodes.ring003.geometry}
          material={materials["マテリアル.001"]}
        />
        <mesh
          name="ring003_1"
          castShadow
          receiveShadow
          geometry={nodes.ring003_1.geometry}
          material={materials.Material}
        />
        <mesh
          name="ring003_2"
          castShadow
          receiveShadow
          geometry={nodes.ring003_2.geometry}
          material={materials["KeyCap-Texture"]}
        />
      </group>
      <mesh
        name="Keycover"
        castShadow
        receiveShadow
        geometry={nodes.Keycover.geometry}
        material={materials.PlasticBottom}
        position={[-2.316, 5.063, 0.172]}
        rotation={[1.62, 0.009, 0.633]}
        scale={[0.806, 0.46, 0.806]}
      />
    </group>
  );
}

useGLTF.preload("/Keychain2.glb");
